$(document).ready(function(){$(".read-more").each(function(){var par=$(this).parent();if(par.index()>1){$(this).hide();}
if(par.index()==1){par.append("<p class=\"read-more-button\">Read More</p>");}});$(".read-more-appeal-button").click(function(){$(this).hide();$(this).parent().parent().find(".read-more").show();$(this).parent().parent().find(".read-more-hide").hide();})
$(".read-more-button").click(function(){$(this).hide();$(this).parent().parent().find(".read-more").show();})
$(".accordion .accordion-content").hide();$(".accordion .accordion-title").click(function(){$(".accordion .accordion-content").not($(this).next(".accordion .accordion-content")).slideUp();$(".accordion .accordion-title").not($(this)).removeClass("open");$(this).next(".accordion .accordion-content").slideToggle();if($(this).hasClass("open")){$(this).removeClass("open");}
else{$(this).addClass("open");}});$("ul li .bulleted-links").each(function(){$(this).parents('li').css("list-style-image","url('/SiteImages/Icons/web-link.png')");});$("ul li .bulleted-number").each(function(){$(this).parents('li').css("list-style-image","url('/SiteImages/Icons/number-link.png')");});$("ul li .bulleted-email").each(function(){$(this).parents('li').css("list-style-image","url('/SiteImages/Icons/email-link.png')");});$("#report-a-crime-continue").click(function(){$(".form.report-a-crime").show();});$("#txtSearch").keyup(function(){$.ajax({type:"POST",url:"/glospolrepository/search/dropdown/",data:"s="+$("#txtSearch").val(),success:function(msg){$('#search-results').html(msg);}});});$("#postcodeBoxLookup").keyup(function(){$.ajax({type:"POST",url:"/glospolrepository/neighbourhood/postcodelookup/",data:"postcode="+$("#postcodeBoxLookup").val(),success:function(data){$("#lookup-results").html(data);$("#lookup-results").show();$("#lpa-list").hide();}});});$('.mobile-navigation-slick').slicknav({prependTo:'.mobile-navigation',label:"Menu",allowParentLinks:true});$(".fancyBox").fancybox({type:'image',helpers:{thumbs:{width:50,height:50}}});$(".id-sought-button").fancybox({fitToView:false,width:'70%',height:'98%',autoSize:false,openEffect:'none',closeEffect:'none'});$(".misconduct-hearing .book-button").fancybox({fitToView:false,width:'70%',height:'98%',autoSize:false,openEffect:'none',closeEffect:'none',padding:0});$("#open-event").fancybox({'width':'70%',maxHeight:'550','autoScale':false,'type':'iframe'});$(".id-sought-form .option input").change(function(){if($(this).attr("id").indexOf("know")>=0||$(this).attr("id").indexOf("suspect")>=0){$(this).parent().parent().siblings(".id-fields").find(".know-suspect").show();$(this).parent().parent().siblings(".id-fields").find(".recognise").hide();}
else{$(this).parent().parent().siblings(".id-fields").find(".know-suspect").hide();$(this).parent().parent().siblings(".id-fields").find(".recognise").show();}})
$(".id-sought-form .contact input").change(function(){if($(this).siblings("label").html().indexOf("Yes")>=0){$(this).parent().parent().siblings(".personal-details").show();}
else{$(this).parent().parent().siblings(".personal-details").hide();}
$(this).parent().parent().siblings(".id-submit-button").show();});$(".id-sought-form .date-picker").datepicker({dateFormat:"dd/mm/yy",yearRange:"-100:+0",changeMonth:true,changeYear:true,maxDate:"0"});$(".twitter-banner .container .flexslider").flexslider({controlNav:false,animationLoop:true});$('.appeals .flexslider').flexslider({slideshow:false});$('.flexslider').flexslider({});$("#hide-all-team").hide();$("#details").hide();$("#view-all-team").click(function(){$(this).hide();$("#hide-all-team").show();$("#all-team").show();});$("#hide-all-team").click(function(){$(this).hide();$("#view-all-team").show();$("#all-team").hide();});$(".close").click(function(){$("#"+this.id).hide();});$(".main-slider-home #news-panel").show().siblings('.panel').hide();$(".main-slider-home #news-arrow").show();$(".main-slider-home .top-bar div").click(function(){var id=$(this).attr("id");$("#"+id).addClass('selected').siblings().removeClass('selected');$("#"+id+"-panel").show().siblings('.panel').hide();$('.main-slider-home .arrow-down').hide();$("#"+id+"-arrow").show();});$(".main-slider-home-mobile .panel").hide();$("#news-mobile").addClass("selected")
$("#news-mobile").next(".arrow-container").show();$("#news-mobile-panel").show();$(".main-slider-home-mobile .slider-title").click(function(){var id=$(this).attr("id");if($(this).hasClass("selected")){$(this).removeClass("selected")
$(this).next(".arrow-container").hide();$("#"+id+"-panel").hide();}
else{$(this).addClass("selected")
$(this).next(".arrow-container").show();$("#"+id+"-panel").show();}});$(".main-slider-local #news-panel").show().siblings('.panel').hide();$(".main-slider-local #news-arrow").show();$(".main-slider-local .top-bar div").click(function(){var id=$(this).attr("id");$("#"+id).addClass('selected').siblings().removeClass('selected');$("#"+id+"-panel").show().siblings('.panel').hide();$('.main-slider-local .arrow-down').hide();$("#"+id+"-arrow").show();});$(".main-slider-local-mobile .panel").hide();$("#news-mobile").addClass("selected")
$("#news-mobile").next(".arrow-container").show();$("#news-mobile-panel").show();$(".main-slider-local-mobile .slider-title").click(function(){var id=$(this).attr("id");if($(this).hasClass("selected")){$(this).removeClass("selected")
$(this).next(".arrow-container").hide();$("#"+id+"-panel").hide();}
else{$(this).addClass("selected")
$(this).next(".arrow-container").show();$("#"+id+"-panel").show();}});$(".about").hide();$(".profile").click(function(){var id=$(this).attr("id");$(".about").hide();$("#officer-"+id).slideToggle();});$(".submit-view").click(function(){var topicID=$(this).attr("id").replace("button","view");$("#"+topicID).parent("div").slideToggle();});var cookieAccept=$.cookie("cookie-accept");var date;var today=new Date();if(cookieAccept!=null){date=new Date(cookieAccept);}
if($.cookie("cookie-accept")==null||date>today){$("#cookie-notice").slideDown();}
$("#cookie-notice .close").click(function(){var expiry=new Date();expiry.setMonth(expiry.getMonth()+6);$.cookie("cookie-accept","1",{expires:expiry});$("#cookie-notice").slideUp();});if($.cookie("contrast")!=null){var contrast=$.cookie("contrast").split(',');setContrast(contrast[0],contrast[1]);}
if($.cookie("fontSize")!=null){setFontSize($.cookie("fontSize"));}
$("#fontIncrease").click(function(){var newSize=18;if($.cookie("fontSize")!=null&&$.cookie("fontSize")!=''){newSize=parseInt($.cookie("fontSize"))+2;}
setFontSize(newSize);var fSize=parseInt($("#fontIncrease").css("font-size"));$("#fontIncrease").css("font-size",fSize+2);fSize=parseInt($("#fontDecrease").css("font-size"));$("#fontDecrease").css("font-size",fSize+2);});$("#fontDecrease").click(function(){var newSize=16;if($.cookie("fontSize")!=null&&$.cookie("fontSize")!=''){newSize=parseInt($.cookie("fontSize"))-2;}
setFontSize(newSize);var fSize=parseInt($("#fontIncrease").css("font-size"));$("#fontIncrease").css("font-size",fSize-2);fSize=parseInt($("#fontDecrease").css("font-size"));$("#fontDecrease").css("font-size",fSize-2);});$("#fontUndo").click(function(){setFontSize('');$("#fontIncrease").css("font-size",'');$("#fontDecrease").css("font-size",'');});$("#blackWhite").click(function(){setContrast('white','black');});$("#whiteBlack").click(function(){setContrast('black','white');});$("#blackBlue").click(function(){setContrast('#a7c7dc','black');});$("#blackYellow").click(function(){setContrast('yellow','black');});$("#contrastUndo").click(function(){setContrast('','');});$(".tile").mouseenter(function(){if($(this).find('.hover').length!=0){$(this).children(".hover").show();$(this).children(".title").hide();}});$(".tile").mouseleave(function(){$(this).children(".hover").hide();$(this).children(".title").show();});$(".event-list-day .event, .event-list-tablet .event").click(function(){if($(this).hasClass("close")){$(".event").removeClass("close");$(".event-details").hide();}
else{$(".event-details").hide();$(".event").removeClass("close");$(this).addClass("close");$("#"+$(this).attr("id").replace("event","details")).show();}});$(".filter-row .area-option input").change(function(){$.ajax({type:"POST",url:"/GlosPolRepository/Mapping/UpdateAreaSession/",data:"{ area: '"+$(this).attr("id")+"'}",contentType:"application/json; charset=utf-8",success:function(){location.reload();}});});$(".filter-row .type-option input").change(function(){$.ajax({type:"POST",url:"/GlosPolRepository/Mapping/UpdateTypeSession/",data:"{ type: '"+$(this).attr("id")+"'}",contentType:"application/json; charset=utf-8",success:function(){location.reload();}});});if($.cookie("message-hide-"+$(".header-container .site-message .close img").attr("id"))==null){$(".site-message").show();}
$(".header-container .site-message .close img").click(function(){$(this).parent().parent().hide();var expiry=new Date($(this).parent().parent().find("#expiry").val());$.cookie("message-hide-"+$(this).attr("id"),true,{path:'/',expires:expiry});});});$(document).mouseup(function(e){var container=$("#search-form");if(!container.is(e.target)&&container.has(e.target).length===0)
{$("#search-results").html("");$("#txtSearch").val("");}});function googleTranslateElementInit(){new google.translate.TranslateElement({pageLanguage:'en'},'google_translate_element');}
function setContrast(background,color){$.cookie("contrast",background+","+color,{path:'/'});$("*").not(".image").not(".slides li").not(".contrast").not("#google_translate_element img").each(function(){$(this).css({'background':background});$(this).css({'color':color});});}
function setFontSize(newSize){$.cookie("fontSize",newSize,{path:'/'});if(newSize!=''){newSize=newSize+"px";}
$("*").not("#fontIncrease, #fontDecrease, .site-title, .site-title a, .site-title a span").each(function(){$(this).css("font-size",newSize);});}
$(window).scroll(function(){var sticky=$('#sticky-bar'),scroll=$(window).scrollTop();var height=0;if($("#emergencyBar").css("display")!="none"){height=$("#emergencyBar").outerHeight();}
$("#sticky-filler").css("height",sticky.outerHeight());if(scroll>=44+height){sticky.addClass('sticky-bar');$("#sticky-filler").css("display","block");}
else{sticky.removeClass('sticky-bar');$("#sticky-filler").css("display","none");}});